### PR TITLE
lab №8

### PR DESCRIPTION
**Pull request by EgorPetko**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Egor.

Since you know how methods works, you can do not use #region (it was done for easier accepting the methods usage)
#region exercise_3_1;
            exercise_3_1();
            #endregion

Task 1. Are you kidding? You must enter a percentage for each letter that is present(!) in the text.

Task 2. Symbols have to be on treir places.
image

**Comment by EgorPetko** [comment]
update

**Comment by NemirovichMark** [comment]
Hello. Almost:
image

**Comment by NemirovichMark** [comment]
Upload changes, that you show me in the class, please.

You can come to class to defend 8th lab.
I will give you more 3 tasks in the class. 
In the solution the methods will be required.

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/9th_Lab

**Pull request merged**
