### PR TITLE
lab 8

### PR DESCRIPTION
**Pull request by zzmtsvv**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Alexey.

Task 1. Foreach cannot work correctly here:
image
image

image

You can use method and send there values from the dictionary or release it with additional array or 2nd dictionary (double values).
Interesting, that you didn't check it before sending the work to me.


Task 2. Symbols should stay on their places.
image

**Comment by zzmtsvv** [comment]
"Interesting, that you didn't check it before sending the work to me." - that's really interesting because everything works well on my laptop
anyway, I'll fix this

**Comment by zzmtsvv** [comment]
fixed

**Comment by NemirovichMark** [comment]
Very interesting.

Seems, I understood why it works on your laptop.
https://makolyte.com/csharp-change-a-dictionarys-values-in-a-foreach-loop/

You can come to class to defend 8th lab.
I will give you more 3 tasks in the class. 
In the solution the methods will be required.

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/9th_Lab

**Pull request merged**
